---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates
spec:
  type: file
  target: ./templates/catalog-info.yaml
#---
#apiVersion: backstage.io/v1alpha1
#kind: Location
#metadata:
#  name: components
#spec:
#  type: file
#  target: ./components/catalog-info.yaml
